# permissions for end users to view podtatoheads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podtatohead-viewer-role
rules:
- apiGroups:
  - podtatohead-demo.podtatohead
  resources:
  - podtatoheads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - podtatohead-demo.podtatohead
  resources:
  - podtatoheads/status
  verbs:
  - get
