# permissions for end users to edit podtatoheads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podtatohead-editor-role
rules:
- apiGroups:
  - podtatohead-demo.podtatohead
  resources:
  - podtatoheads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podtatohead-demo.podtatohead
  resources:
  - podtatoheads/status
  verbs:
  - get
